#version 450
// glslangValidator shader.comp -V -q -e main -o shader.spv -DCOPYADD

layout(binding = 0) readonly buffer inputfile0
{
    ivec4 matrices[];
} sourceFile;

layout(binding = 1) buffer outputfile0
{
    ivec4 matrices[];
} outputFile;

layout(binding = 2) readonly buffer inputdir0
{
    ivec4 matrices[];
} sourceDir;

layout(binding = 3) buffer outputdir0
{
    ivec4 matrices[];
} outputDir;

layout(binding = 4) buffer temporary0
{
    ivec4 matrices[];
} temporary;

#ifdef COPY
layout (local_size_x = 64) in;
void main() 
{		
	uint gID = gl_GlobalInvocationID.x;
    outputDir.matrices[gID] = sourceDir.matrices[gID] + sourceFile.matrices[gID];
	outputFile.matrices[gID] += sourceFile.matrices[gID];
}
#endif

#ifdef COPYADD
layout (local_size_x = 64) in;
void main() 
{		
	uint gID = gl_GlobalInvocationID.x;
    outputDir.matrices[gID] = sourceDir.matrices[gID] + 1;
}
#endif

